# **Module**: Python Installation and Basics
## **Lecture**: Scientific Computing Package - Numpy

> ## Numpy introduction

In [1]:
# inconvenience with lists
list1 = [2,3,4]
list1_doubled = 2*list1

print(list1_doubled)

[2, 3, 4, 2, 3, 4]


In [2]:
# create a 1D array
import numpy as np

arr1D = np.array([2,3,4]) 
print('arr1D: ', arr1D)

# double each item in arr1D
arr1D_doubled = 2*arr1D
print('arr1D_doubled: ', arr1D_doubled)

# get information about arr1D
print('Number of items in arr1D: ', arr1D.size)
print('Dimensionality of arr1D: ', arr1D.ndim)
print('Shape of arr1D: ', arr1D.shape) # number of items along each dimension

arr1D:  [2 3 4]
arr1D_doubled:  [4 6 8]
Number of items in arr1D:  3
Dimensionality of arr1D:  1
Shape of arr1D:  (3,)


In [3]:
# create a 2D array
import numpy as np

arr2D = np.array([[1,4,6],[2,5,7]]) 
print('arr2D: \n', arr2D)

# get information about arr2D
print('Number of items in arr2D: ', arr2D.size)
print('Dimensionality of arr2D: ', arr2D.ndim)
print('Shape of arr2D: ', arr2D.shape) # number of items along each dimension


arr2D: 
 [[1 4 6]
 [2 5 7]]
Number of items in arr2D:  6
Dimensionality of arr2D:  2
Shape of arr2D:  (2, 3)


> ## Creating Numpy Arrays 

In [4]:
# creating sequence of numbers
arr1 = np.arange(3, 9) # same as Python range function
print('arr1: ', arr1)

arr2 = np.arange(3, 9, 2) # the 3rd argument defines the step size
print('arr2: ', arr2)

arr3 = np.linspace(3,9,3) # creates evenly spaced 3 values from 1 to 9
print('arr3: ', arr3)

arr1:  [3 4 5 6 7 8]
arr2:  [3 5 7]
arr3:  [3. 6. 9.]


In [5]:
# creating special arrays
arr4 = np.ones((2,1)) # array of shape (2,1) with all items as 1
print('arr4: \n', arr4)

arr4 = np.ones((2,1), dtype=int) # array of shape (2,1) with all items as 1
print('arr4: \n', arr4)

arr5 = np.zeros((2,2)) # all items as zero
print('arr5: \n', arr5)

arr6 = np.eye(2) # diagonal items as 1
print('arr6: \n', arr6)

arr4: 
 [[1.]
 [1.]]
arr4: 
 [[1]
 [1]]
arr5: 
 [[0. 0.]
 [0. 0.]]
arr6: 
 [[1. 0.]
 [0. 1.]]


In [6]:
# adding axis to existing arrays (e.g., converting 1D array to 2D array)
print('arr1: ', arr1)
print('arr1 in 2D: \n', arr1[:, np.newaxis])

arr7 = arr1[:, None] # same as above
print('\n arr7: \n', arr7)

arr1:  [3 4 5 6 7 8]
arr1 in 2D: 
 [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]

 arr7: 
 [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [7]:
# combining / stacking arrays
arr1 = np.array([3,4,5])
print('arr1: ', arr1)

arr2 = np.array([3,5,7])
print('arr2: ', arr2)

print('\narr4: \n', arr4)
print('\narr5: \n', arr5)
print('\narr6: \n', arr6)

print('\n----stack arrays horizontally----- \n')
print('arr1 and arr2: ', np.hstack((arr1, arr2))) # horizontally stacks passed arrays
print('arr5 and arr4: \n', np.hstack((arr5,arr4))) # array 4 added as a column into arr5

print('\n----stack arrays vertically---- \n')
print('arr1 and arr2: \n', np.vstack((arr1, arr2))) # vertically stacks passed arrays
print('arr5 and arr6: \n', np.vstack((arr5,arr6))) # rows of array 6 added onto arr5

arr1:  [3 4 5]
arr2:  [3 5 7]

arr4: 
 [[1]
 [1]]

arr5: 
 [[0. 0.]
 [0. 0.]]

arr6: 
 [[1. 0.]
 [0. 1.]]

----stack arrays horizontally----- 

arr1 and arr2:  [3 4 5 3 5 7]
arr5 and arr4: 
 [[0. 0. 1.]
 [0. 0. 1.]]

----stack arrays vertically---- 

arr1 and arr2: 
 [[3 4 5]
 [3 5 7]]
arr5 and arr6: 
 [[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]]


> ## Numpy Functions

In [8]:
# basic numpy functions
print('arr2D: \n', arr2D)

print('Summing up values along the rows of arr2D: ', arr2D.sum(axis=0))
print('Summing up values along the columns of arr2D: ', arr2D.sum(axis=1))
print('Summing up all the values of arr2D: ', arr2D.sum())

arr2D: 
 [[1 4 6]
 [2 5 7]]
Summing up values along the rows of arr2D:  [ 3  9 13]
Summing up values along the columns of arr2D:  [11 14]
Summing up all the values of arr2D:  25


> ## Logical Operations

In [9]:
array1 = np.array([[5,4,3],[2,1,0]])
print('array1: \n', array1)

array2 = np.array([[0,1,0],[2,0,1]])
print('array2: \n', array2)

array1: 
 [[5 4 3]
 [2 1 0]]
array2: 
 [[0 1 0]
 [2 0 1]]


In [10]:
# element-wise OR operation
print('element-wise OR operation: \n', np.logical_or(array1>3, array2==1))

# element-wise AND operation
print('element-wise AND operation: \n', np.logical_and(array1>3, array2==1))


element-wise OR operation: 
 [[ True  True False]
 [False False  True]]
element-wise AND operation: 
 [[False  True False]
 [False False False]]


In [11]:
# check if all elements are TRUE
np.all(array2 > 0)

False

In [12]:
# check if any element is TRUE
np.any(array2 > 0)

True

> ## Indexing and Slicing Arrays

In [13]:
# accessing individual items
print('arr2D: \n', arr2D)
print(arr2D[1,2])

arr2D: 
 [[1 4 6]
 [2 5 7]]
7


In [14]:
# slicing
array3 = np.arange(10).reshape((2,5)) # rearrange the 1D array into shape (2,5)
print('array3: \n', array3)

print('\n')
print((array3[0:1,1:3]))
print((array3[0,1:3])) # note that a 1D array is returned here instead of the 2D array above

array3: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


[[1 2]]
[1 2]


In [15]:
# accessing entire row or column
print(array3[1]) # returns 2nd row; same as array3[1,:]
print(array3[:, 4]) # returns items of 3rd column as a 1D array 

[5 6 7 8 9]
[4 9]


> ## Working with Views versus Copies

In [16]:
# extract a subarray from arr8 and modify it
print('array3: \n', array3)

array3_sub = array3[:, :2] # columns 0 and 1 from all rows
array3_sub[1, 1] = 1000
print('array3 after view modification: \n', array3) # array3 gets modified as well!! 

array3: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 after view modification: 
 [[   0    1    2    3    4]
 [   5 1000    7    8    9]]


In [17]:
# use copy method for a separate copy
array3 = np.arange(10).reshape((2,5))
print('array3: \n', array3)

array3_sub2 = array3[:, :2].copy()
array3_sub2[1, 1] = 100
print('array3 after copy modification: \n', array3)

array3: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 after copy modification: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


> ### scenarios where slicing returns a copy and not a view

In [20]:
# Fancy indexing
# combination of simple and fancy indexing
array3_sub3 = array3[:, [0, 1]] # note how columns are indexed via a list
array3_sub3[1, 1] = 100
print('array3 after copy modification: \n', array3)

# use boolean mask to select subarray
array3_sub4 = array3[array3 > 5] 
array3_sub4[0] = 0
print('array3 after copy modification: \n', array3)

array3 after copy modification: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 after copy modification: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
